# Generated by Django 3.1.7 on 2021-06-11 08:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authoringtool', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaphore', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField(verbose_name='Last semaphore update')),
                ('microcontent', models.ManyToManyField(to='authoringtool.MicroContent')),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='Action time')),
                ('microcontent', models.ManyToManyField(to='authoringtool.MicroContent')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('courses', models.ManyToManyField(to='authoringtool.Playlist')),
                ('states', models.ManyToManyField(to='studentsmanager.State')),
                ('tracking', models.ManyToManyField(to='studentsmanager.Trace')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
