# Generated by Django 3.1.7 on 2021-06-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='semaphore',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='action',
            field=models.CharField(max_length=2000),
        ),
    ]
