# Generated by Django 3.1.7 on 2021-07-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0002_auto_20210613_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alexa_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
