# Generated by Django 3.1.7 on 2021-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0004_auto_20210705_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
