# Generated by Django 3.1.7 on 2022-04-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0006_configvalues'),
        ('studentsmanager', '0006_student_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Keywords_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('semaphore', models.CharField(default='red', max_length=200)),
                ('configValues', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authoringtool.configvalues')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='keywords_states',
            field=models.ManyToManyField(to='studentsmanager.Keywords_State'),
        ),
    ]
