# Generated by Django 3.1.7 on 2022-04-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0008_auto_20220422_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords_state',
            name='configValues',
        ),
    ]
