# Generated by Django 3.1.7 on 2022-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0009_remove_keywords_state_configvalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords_state',
            old_name='alreadydone',
            new_name='alreadydoneII',
        ),
        migrations.AddField(
            model_name='keywords_state',
            name='alreadydoneIII',
            field=models.CharField(default='', max_length=200),
        ),
    ]
