# Generated by Django 4.0.4 on 2022-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0010_auto_20220511_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
