# Generated by Django 4.0.4 on 2022-05-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0011_student_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=400)),
                ('time', models.DateTimeField(verbose_name='Comment Time')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.ManyToManyField(to='studentsmanager.comments'),
        ),
    ]
