# Generated by Django 4.0.4 on 2022-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsmanager', '0012_comments_student_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace',
            name='microcontent',
        ),
        migrations.AddField(
            model_name='trace',
            name='microcontent',
            field=models.CharField(default='aprendeii', max_length=200),
        ),
    ]
