# Generated by Django 3.1.7 on 2021-06-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('upload_form', models.CharField(default='', max_length=50, null=True)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('mediaFile', models.FileField(null=True, upload_to='')),
                ('text', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('last_modification', models.DateTimeField(verbose_name='Last modification')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=300)),
                ('first_choice', models.CharField(default='', max_length=300)),
                ('second_choice', models.CharField(default='', max_length=300)),
                ('third_choice', models.CharField(default='', max_length=300)),
                ('correct_answer', models.CharField(default='', max_length=300)),
                ('explanation', models.TextField(default='')),
                ('order_in_questionnaire', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SortedMicrocontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_playlist', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MicroContent',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authoringtool.metadata')),
                ('show', models.CharField(max_length=10, null=True)),
                ('media', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authoringtool.media')),
            ],
        ),
        migrations.CreateModel(
            name='Prequestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(to='authoringtool.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Postquestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(to='authoringtool.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('show', models.CharField(max_length=10, null=True)),
                ('microcontent_list', models.ManyToManyField(to='authoringtool.SortedMicrocontent')),
            ],
        ),
        migrations.AddField(
            model_name='sortedmicrocontent',
            name='microcontent',
            field=models.ManyToManyField(to='authoringtool.MicroContent'),
        ),
        migrations.AddField(
            model_name='microcontent',
            name='post_questionaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authoringtool.postquestionnaire'),
        ),
        migrations.AddField(
            model_name='microcontent',
            name='pre_questionaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authoringtool.prequestionnaire'),
        ),
    ]
