# Generated by Django 3.1.7 on 2021-07-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='microcontent',
            name='keywords',
            field=models.ManyToManyField(to='authoringtool.Keyword'),
        ),
    ]
