# Generated by Django 3.1.7 on 2021-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0002_auto_20210716_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='id_telegram',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
