# Generated by Django 3.1.7 on 2022-02-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0003_media_id_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontent',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microcontent',
            name='playlist',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
