# Generated by Django 3.1.7 on 2022-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0005_auto_20220218_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeI', models.IntegerField(default=5)),
                ('typeII', models.IntegerField(default=1)),
                ('typeIII', models.IntegerField(default=2)),
                ('level_red_orange', models.IntegerField(default=8)),
                ('level_orange_green', models.IntegerField(default=10)),
            ],
        ),
    ]
